from vietnam_routes import auto_desc, build_custom_accordion, build_custom_sidebar

# ── Spain Sidebar (58 destinations, 10 groups, 3-column grid) ─────────────────

SPAIN_SIDEBAR = [
    ("Europe & UK", "region-europe-usa", [
        "UK",              "France",          "Germany",
        "Switzerland",     "Netherlands",     "Belgium",
        "Portugal",        "Italy",           "Ireland",
    ]),
    ("Nordic & Scandinavia", "region-europe-usa", [
        "Denmark",         "Sweden",          "Norway",
        "Finland",
    ]),
    ("Eastern & Central Europe", "region-europe-usa", [
        "Austria",         "Poland",          "Czech Republic",
        "Greece",          "Romania",
    ]),
    ("Middle East & GCC", "region-middle-east", [
        "UAE",             "Saudi Arabia",    "Qatar",
        "Oman",            "Kuwait",          "Bahrain",
        "Jordan",          "Iraq",
    ]),
    ("Asia & Subcontinent", "region-asia", [
        "India",           "Pakistan",        "Bangladesh",
        "Nepal",           "Maldives",        "Thailand",
        "Singapore",       "Malaysia",        "China",
        "Japan",           "South Korea",
    ]),
    ("North Africa", "region-africa", [
        "Morocco",         "Algeria",         "Tunisia",
        "Egypt",
    ]),
    ("Africa", "region-africa", [
        "Kenya",           "Nigeria",         "Ethiopia",
        "South Africa",    "Senegal",
    ]),
    ("USA & Canada", "region-europe-usa", [
        "USA",             "Canada",
    ]),
    ("Latin America", "region-europe-usa", [
        "Mexico",          "Brazil",          "Argentina",
        "Colombia",        "Peru",            "Chile",
        "Panama",          "Ecuador",
    ]),
    ("Oceania", "region-oceania", [
        "Australia",       "New Zealand",
    ]),
]

# ── Spain Route Cards (77 cards, domestic + international) ────────────────────
# Fully expanded from user input. All descriptions auto-generated.

SPAIN_ROUTE_CARDS = [
    # ── Domestic Spain (25 cards) ─────────────────────────────────────────────
    ("Madrid",             "Barcelona",      auto_desc("Madrid",             "Barcelona")),
    ("Madrid",             "Valencia",       auto_desc("Madrid",             "Valencia")),
    ("Madrid",             "Seville",        auto_desc("Madrid",             "Seville")),
    ("Madrid",             "Málaga",         auto_desc("Madrid",             "Málaga")),
    ("Barcelona",          "Madrid",         auto_desc("Barcelona",          "Madrid")),
    ("Barcelona",          "Valencia",       auto_desc("Barcelona",          "Valencia")),
    ("Barcelona",          "Bilbao",         auto_desc("Barcelona",          "Bilbao")),
    ("Barcelona",          "Málaga",         auto_desc("Barcelona",          "Málaga")),
    ("Málaga",             "Madrid",         auto_desc("Málaga",             "Madrid")),
    ("Málaga",             "Barcelona",      auto_desc("Málaga",             "Barcelona")),
    ("Málaga",             "Seville",        auto_desc("Málaga",             "Seville")),
    ("Valencia",           "Madrid",         auto_desc("Valencia",           "Madrid")),
    ("Valencia",           "Barcelona",      auto_desc("Valencia",           "Barcelona")),
    ("Valencia",           "Alicante",       auto_desc("Valencia",           "Alicante")),
    ("Seville",            "Madrid",         auto_desc("Seville",            "Madrid")),
    ("Seville",            "Barcelona",      auto_desc("Seville",            "Barcelona")),
    ("Seville",            "Málaga",         auto_desc("Seville",            "Málaga")),
    ("Bilbao",             "Madrid",         auto_desc("Bilbao",             "Madrid")),
    ("Bilbao",             "Barcelona",      auto_desc("Bilbao",             "Barcelona")),
    ("Alicante",           "Madrid",         auto_desc("Alicante",           "Madrid")),
    ("Alicante",           "Barcelona",      auto_desc("Alicante",           "Barcelona")),
    ("Alicante",           "Valencia",       auto_desc("Alicante",           "Valencia")),
    ("Palma de Mallorca",  "Madrid",         auto_desc("Palma de Mallorca",  "Madrid")),
    ("Palma de Mallorca",  "Barcelona",      auto_desc("Palma de Mallorca",  "Barcelona")),
    ("Palma de Mallorca",  "Valencia",       auto_desc("Palma de Mallorca",  "Valencia")),

    # ── Europe (22 cards) ─────────────────────────────────────────────────────
    ("Madrid",             "London",         auto_desc("Madrid",             "London")),
    ("Madrid",             "Manchester",     auto_desc("Madrid",             "Manchester")),
    ("Barcelona",          "London",         auto_desc("Barcelona",          "London")),
    ("Barcelona",          "Manchester",     auto_desc("Barcelona",          "Manchester")),
    ("Madrid",             "Frankfurt",      auto_desc("Madrid",             "Frankfurt")),
    ("Madrid",             "Munich",         auto_desc("Madrid",             "Munich")),
    ("Madrid",             "Berlin",         auto_desc("Madrid",             "Berlin")),
    ("Barcelona",          "Frankfurt",      auto_desc("Barcelona",          "Frankfurt")),
    ("Barcelona",          "Munich",         auto_desc("Barcelona",          "Munich")),
    ("Barcelona",          "Berlin",         auto_desc("Barcelona",          "Berlin")),
    ("Madrid",             "Paris",          auto_desc("Madrid",             "Paris")),
    ("Madrid",             "Lyon",           auto_desc("Madrid",             "Lyon")),
    ("Barcelona",          "Paris",          auto_desc("Barcelona",          "Paris")),
    ("Barcelona",          "Lyon",           auto_desc("Barcelona",          "Lyon")),
    ("Madrid",             "Zurich",         auto_desc("Madrid",             "Zurich")),
    ("Madrid",             "Geneva",         auto_desc("Madrid",             "Geneva")),
    ("Barcelona",          "Zurich",         auto_desc("Barcelona",          "Zurich")),
    ("Barcelona",          "Geneva",         auto_desc("Barcelona",          "Geneva")),
    ("Madrid",             "Amsterdam",      auto_desc("Madrid",             "Amsterdam")),
    ("Madrid",             "Rotterdam",      auto_desc("Madrid",             "Rotterdam")),
    ("Barcelona",          "Amsterdam",      auto_desc("Barcelona",          "Amsterdam")),
    ("Barcelona",          "Rotterdam",      auto_desc("Barcelona",          "Rotterdam")),

    # ── Middle East (6 cards) ─────────────────────────────────────────────────
    ("Madrid",             "Dubai",          auto_desc("Madrid",             "Dubai")),
    ("Madrid",             "Abu Dhabi",      auto_desc("Madrid",             "Abu Dhabi")),
    ("Barcelona",          "Dubai",          auto_desc("Barcelona",          "Dubai")),
    ("Barcelona",          "Abu Dhabi",      auto_desc("Barcelona",          "Abu Dhabi")),
    ("Madrid",             "Riyadh",         auto_desc("Madrid",             "Riyadh")),
    ("Madrid",             "Jeddah",         auto_desc("Madrid",             "Jeddah")),
    ("Barcelona",          "Riyadh",         auto_desc("Barcelona",          "Riyadh")),
    ("Barcelona",          "Jeddah",         auto_desc("Barcelona",          "Jeddah")),
    ("Madrid",             "Doha",           auto_desc("Madrid",             "Doha")),
    ("Barcelona",          "Doha",           auto_desc("Barcelona",          "Doha")),

    # ── Asia (8 cards) ────────────────────────────────────────────────────────
    ("Madrid",             "Delhi",          auto_desc("Madrid",             "Delhi")),
    ("Madrid",             "Mumbai",         auto_desc("Madrid",             "Mumbai")),
    ("Madrid",             "Bengaluru",      auto_desc("Madrid",             "Bengaluru")),
    ("Madrid",             "Kochi",          auto_desc("Madrid",             "Kochi")),
    ("Barcelona",          "Delhi",          auto_desc("Barcelona",          "Delhi")),
    ("Barcelona",          "Mumbai",         auto_desc("Barcelona",          "Mumbai")),
    ("Barcelona",          "Bengaluru",      auto_desc("Barcelona",          "Bengaluru")),
    ("Barcelona",          "Kochi",          auto_desc("Barcelona",          "Kochi")),

    # ── Americas (8 cards) ────────────────────────────────────────────────────
    ("Madrid",             "New York",       auto_desc("Madrid",             "New York")),
    ("Madrid",             "Miami",          auto_desc("Madrid",             "Miami")),
    ("Barcelona",          "New York",       auto_desc("Barcelona",          "New York")),
    ("Barcelona",          "Miami",          auto_desc("Barcelona",          "Miami")),
    ("Madrid",             "Toronto",        auto_desc("Madrid",             "Toronto")),
    ("Madrid",             "Vancouver",      auto_desc("Madrid",             "Vancouver")),
    ("Barcelona",          "Toronto",        auto_desc("Barcelona",          "Toronto")),
    ("Barcelona",          "Vancouver",      auto_desc("Barcelona",          "Vancouver")),

    # ── Africa (4 cards) ──────────────────────────────────────────────────────
    ("Madrid",             "Casablanca",     auto_desc("Madrid",             "Casablanca")),
    ("Madrid",             "Marrakech",      auto_desc("Madrid",             "Marrakech")),
    ("Barcelona",          "Casablanca",     auto_desc("Barcelona",          "Casablanca")),
    ("Barcelona",          "Marrakech",      auto_desc("Barcelona",          "Marrakech")),
]

# ── Spain Accordion (5 sections) ──────────────────────────────────────────────

SPAIN_ACCORDION = {
    "asia": [
        # Madrid
        ("Madrid", "Delhi"),       ("Madrid", "Mumbai"),      ("Madrid", "Bengaluru"),
        ("Madrid", "Islamabad"),   ("Madrid", "Lahore"),      ("Madrid", "Karachi"),
        ("Madrid", "Dhaka"),
        ("Madrid", "Kathmandu"),
        ("Madrid", "Malé"),
        ("Madrid", "Bangkok"),
        ("Madrid", "Singapore"),
        ("Madrid", "Kuala Lumpur"),
        ("Madrid", "Beijing"),     ("Madrid", "Shanghai"),
        ("Madrid", "Tokyo"),
        ("Madrid", "Seoul"),
        # Barcelona
        ("Barcelona", "Delhi"),    ("Barcelona", "Mumbai"),
        ("Barcelona", "Islamabad"),("Barcelona", "Lahore"),
        ("Barcelona", "Bangkok"),
        ("Barcelona", "Singapore"),
        ("Barcelona", "Beijing"),  ("Barcelona", "Shanghai"),
        ("Barcelona", "Tokyo"),
        ("Barcelona", "Seoul"),
    ],
    "middle_east": [
        # Madrid
        ("Madrid", "Dubai"),       ("Madrid", "Abu Dhabi"),
        ("Madrid", "Riyadh"),      ("Madrid", "Jeddah"),
        ("Madrid", "Doha"),
        ("Madrid", "Muscat"),
        ("Madrid", "Kuwait City"),
        ("Madrid", "Manama"),
        ("Madrid", "Amman"),
        ("Madrid", "Baghdad"),
        # Barcelona
        ("Barcelona", "Dubai"),    ("Barcelona", "Abu Dhabi"),
        ("Barcelona", "Riyadh"),   ("Barcelona", "Jeddah"),
        ("Barcelona", "Doha"),
        ("Barcelona", "Muscat"),
    ],
    "europe_usa": [
        # ── USA ──────────────────────────────────────────────────────────────
        ("Madrid",            "New York"),    ("Madrid",            "Miami"),
        ("Madrid",            "Boston"),      ("Madrid",            "Chicago"),
        ("Barcelona",         "New York"),    ("Barcelona",         "Boston"),
        ("Barcelona",         "Miami"),
        ("Málaga",            "New York"),
        # ── Canada ───────────────────────────────────────────────────────────
        ("Madrid",            "Toronto"),     ("Madrid",            "Montreal"),
        ("Barcelona",         "Toronto"),     ("Barcelona",         "Montreal"),
        ("Palma de Mallorca", "Montreal"),
        ("Valencia",          "Montreal"),
        # ── Europe — Madrid ──────────────────────────────────────────────────
        ("Madrid", "London"),       ("Madrid", "Manchester"),   ("Madrid", "Birmingham"),
        ("Madrid", "Paris"),        ("Madrid", "Lyon"),         ("Madrid", "Nice"),
        ("Madrid", "Frankfurt"),    ("Madrid", "Munich"),       ("Madrid", "Berlin"),
        ("Madrid", "Zurich"),       ("Madrid", "Geneva"),
        ("Madrid", "Amsterdam"),
        ("Madrid", "Brussels"),
        ("Madrid", "Lisbon"),       ("Madrid", "Porto"),
        ("Madrid", "Rome"),         ("Madrid", "Milan"),
        ("Madrid", "Dublin"),
        ("Madrid", "Vienna"),
        ("Madrid", "Copenhagen"),
        ("Madrid", "Stockholm"),
        ("Madrid", "Oslo"),
        ("Madrid", "Helsinki"),
        ("Madrid", "Warsaw"),       ("Madrid", "Kraków"),
        ("Madrid", "Prague"),
        ("Madrid", "Athens"),
        ("Madrid", "Bucharest"),
        # ── Europe — Barcelona ───────────────────────────────────────────────
        ("Barcelona", "London"),    ("Barcelona", "Manchester"),
        ("Barcelona", "Paris"),     ("Barcelona", "Lyon"),
        ("Barcelona", "Frankfurt"), ("Barcelona", "Munich"),    ("Barcelona", "Berlin"),
        ("Barcelona", "Zurich"),    ("Barcelona", "Geneva"),
        ("Barcelona", "Amsterdam"),
        ("Barcelona", "Brussels"),
        ("Barcelona", "Rome"),      ("Barcelona", "Milan"),
        ("Barcelona", "Lisbon"),    ("Barcelona", "Porto"),
        ("Barcelona", "Dublin"),
        ("Barcelona", "Vienna"),
        ("Barcelona", "Copenhagen"),
        ("Barcelona", "Stockholm"),
        ("Barcelona", "Oslo"),
        ("Barcelona", "Helsinki"),
        ("Barcelona", "Warsaw"),
        ("Barcelona", "Prague"),
        ("Barcelona", "Athens"),
        # ── Europe — Málaga ──────────────────────────────────────────────────
        ("Málaga", "London"),       ("Málaga", "Manchester"),   ("Málaga", "Birmingham"),
        ("Málaga", "Paris"),        ("Málaga", "Marseille"),
        ("Málaga", "Frankfurt"),    ("Málaga", "Munich"),       ("Málaga", "Düsseldorf"),
        ("Málaga", "Zurich"),       ("Málaga", "Geneva"),       ("Málaga", "Basel"),
        ("Málaga", "Amsterdam"),    ("Málaga", "Eindhoven"),
        ("Málaga", "Brussels"),
        ("Málaga", "Dublin"),       ("Málaga", "Cork"),
        ("Málaga", "Copenhagen"),
        ("Málaga", "Stockholm"),
        ("Málaga", "Oslo"),
        ("Málaga", "Helsinki"),
        ("Málaga", "Vienna"),
        ("Málaga", "Prague"),
        ("Málaga", "Warsaw"),       ("Málaga", "Kraków"),
        ("Málaga", "Rome"),         ("Málaga", "Milan"),
        ("Málaga", "Lisbon"),       ("Málaga", "Porto"),
        # ── Europe — Alicante ────────────────────────────────────────────────
        ("Alicante", "London"),     ("Alicante", "Manchester"), ("Alicante", "Birmingham"),
        ("Alicante", "Frankfurt"),  ("Alicante", "Munich"),
        ("Alicante", "Amsterdam"),
        ("Alicante", "Brussels"),
        ("Alicante", "Paris"),
        ("Alicante", "Zurich"),     ("Alicante", "Geneva"),
        ("Alicante", "Dublin"),
        ("Alicante", "Copenhagen"),
        ("Alicante", "Stockholm"),
        ("Alicante", "Oslo"),
        ("Alicante", "Helsinki"),
        ("Alicante", "Warsaw"),     ("Alicante", "Kraków"),
        ("Alicante", "Prague"),
        ("Alicante", "Rome"),       ("Alicante", "Milan"),
        ("Alicante", "Lisbon"),
        # ── Europe — Palma de Mallorca ───────────────────────────────────────
        ("Palma de Mallorca", "London"),      ("Palma de Mallorca", "Manchester"),
        ("Palma de Mallorca", "Frankfurt"),   ("Palma de Mallorca", "Munich"),
        ("Palma de Mallorca", "Düsseldorf"),
        ("Palma de Mallorca", "Paris"),
        ("Palma de Mallorca", "Zurich"),      ("Palma de Mallorca", "Geneva"),
        ("Palma de Mallorca", "Basel"),
        ("Palma de Mallorca", "Amsterdam"),
        ("Palma de Mallorca", "Brussels"),
        ("Palma de Mallorca", "Vienna"),
        ("Palma de Mallorca", "Copenhagen"),
        ("Palma de Mallorca", "Stockholm"),
        ("Palma de Mallorca", "Oslo"),
        ("Palma de Mallorca", "Helsinki"),
        ("Palma de Mallorca", "Dublin"),
        ("Palma de Mallorca", "Rome"),        ("Palma de Mallorca", "Milan"),
        # ── Europe — Valencia ────────────────────────────────────────────────
        ("Valencia", "London"),
        ("Valencia", "Paris"),
        ("Valencia", "Frankfurt"),  ("Valencia", "Munich"),
        ("Valencia", "Amsterdam"),
        ("Valencia", "Zurich"),
        ("Valencia", "Brussels"),
        ("Valencia", "Rome"),       ("Valencia", "Milan"),
        ("Valencia", "Lisbon"),
        ("Valencia", "Vienna"),
        ("Valencia", "Helsinki"),
        # ── Europe — Seville ─────────────────────────────────────────────────
        ("Seville", "London"),
        ("Seville", "Paris"),
        ("Seville", "Frankfurt"),   ("Seville", "Munich"),
        ("Seville", "Amsterdam"),
        ("Seville", "Rome"),        ("Seville", "Milan"),
        ("Seville", "Lisbon"),      ("Seville", "Porto"),
        # ── Europe — Bilbao ──────────────────────────────────────────────────
        ("Bilbao", "London"),
        ("Bilbao", "Paris"),
        ("Bilbao", "Frankfurt"),    ("Bilbao", "Munich"),
        ("Bilbao", "Amsterdam"),
        ("Bilbao", "Zurich"),
        ("Bilbao", "Brussels"),
        ("Bilbao", "Lisbon"),
        # ── Europe — Tenerife ────────────────────────────────────────────────
        ("Tenerife", "London"),     ("Tenerife", "Manchester"),
        ("Tenerife", "Frankfurt"),  ("Tenerife", "Munich"),
        ("Tenerife", "Amsterdam"),
        ("Tenerife", "Paris"),
        ("Tenerife", "Zurich"),
        ("Tenerife", "Brussels"),
        ("Tenerife", "Dublin"),
        ("Tenerife", "Copenhagen"),
        ("Tenerife", "Stockholm"),
        ("Tenerife", "Oslo"),
        # ── Europe — Gran Canaria ────────────────────────────────────────────
        ("Gran Canaria", "London"),     ("Gran Canaria", "Manchester"),
        ("Gran Canaria", "Frankfurt"),  ("Gran Canaria", "Munich"),
        ("Gran Canaria", "Amsterdam"),
        ("Gran Canaria", "Paris"),
        ("Gran Canaria", "Zurich"),
        ("Gran Canaria", "Brussels"),
        ("Gran Canaria", "Copenhagen"),
        ("Gran Canaria", "Bergen"),     ("Gran Canaria", "Stavanger"),
        ("Gran Canaria", "Oslo"),
        ("Gran Canaria", "Stockholm"),
    ],
    "oceania": [
        ("Madrid",    "Sydney"),    ("Madrid",    "Melbourne"), ("Madrid",    "Auckland"),
        ("Barcelona", "Sydney"),    ("Barcelona", "Melbourne"), ("Barcelona", "Auckland"),
    ],
    "africa": [
        # Madrid
        ("Madrid", "Casablanca"),   ("Madrid", "Marrakech"),
        ("Madrid", "Algiers"),
        ("Madrid", "Tunis"),
        ("Madrid", "Cairo"),
        ("Madrid", "Nairobi"),
        ("Madrid", "Lagos"),        ("Madrid", "Abuja"),
        ("Madrid", "Addis Ababa"),
        ("Madrid", "Johannesburg"), ("Madrid", "Cape Town"),
        ("Madrid", "Dakar"),
        # Barcelona
        ("Barcelona", "Casablanca"),("Barcelona", "Marrakech"),
        ("Barcelona", "Algiers"),
        ("Barcelona", "Cairo"),
        ("Barcelona", "Nairobi"),
        ("Barcelona", "Lagos"),
        # Málaga
        ("Málaga", "Casablanca"),   ("Málaga", "Marrakech"),
        ("Málaga", "Rabat"),        ("Málaga", "Tangier"),
        # Alicante
        ("Alicante", "Casablanca"), ("Alicante", "Marrakech"),
        # Seville
        ("Seville", "Casablanca"),  ("Seville", "Marrakech"),
    ],
}
