from vietnam_routes import auto_desc, build_custom_accordion, build_custom_sidebar

# ── Tanzania Sidebar (39 destinations, 5 groups, 3-column grid) ───────────────

TANZANIA_SIDEBAR = [
    ("Asia & Subcontinent", "region-asia", [
        "India",       "Sri Lanka",     "Bangladesh",
        "Pakistan",    "Nepal",         "Maldives",
        "Thailand",    "Malaysia",      "Singapore",
    ]),
    ("Middle East", "region-middle-east", [
        "UAE",          "Qatar",         "Oman",
        "Saudi Arabia", "Kuwait",        "Bahrain",
    ]),
    ("Africa", "region-africa", [
        "Kenya",        "South Africa",  "Ethiopia",
        "Uganda",       "Rwanda",        "Zambia",
        "Zimbabwe",     "Mozambique",    "Malawi",
        "Mauritius",    "Seychelles",    "Nigeria",
    ]),
    ("Europe", "region-europe-usa", [
        "UK",           "Germany",       "France",
        "Netherlands",  "Switzerland",   "Italy",
        "Spain",        "Belgium",       "Türkiye",
    ]),
    ("North America & Oceania", "region-oceania", [
        "USA",          "Canada",        "Australia",
    ]),
]

# ── Tanzania Route Cards (19 cards) ───────────────────────────────────────────

TANZANIA_ROUTE_CARDS = [
    ("Dar es Salaam",        "Delhi",         auto_desc("Dar es Salaam",        "Delhi")),
    ("Dar es Salaam",        "Mumbai",        auto_desc("Dar es Salaam",        "Mumbai")),
    ("Dar es Salaam",        "Hyderabad",     auto_desc("Dar es Salaam",        "Hyderabad")),
    ("Dar es Salaam",        "Chennai",       auto_desc("Dar es Salaam",        "Chennai")),
    ("Dar es Salaam",        "Bengaluru",     auto_desc("Dar es Salaam",        "Bengaluru")),
    ("Zanzibar",             "Mumbai",        auto_desc("Zanzibar",             "Mumbai")),
    ("Zanzibar",             "Delhi",         auto_desc("Zanzibar",             "Delhi")),
    ("Zanzibar",             "Kochi",         auto_desc("Zanzibar",             "Kochi")),
    ("Arusha / Kilimanjaro", "Delhi",         auto_desc("Arusha / Kilimanjaro", "Delhi")),
    ("Arusha / Kilimanjaro", "Mumbai",        auto_desc("Arusha / Kilimanjaro", "Mumbai")),
    ("Dar es Salaam",        "Nairobi",       auto_desc("Dar es Salaam",        "Nairobi")),
    ("Arusha / Kilimanjaro", "Nairobi",       auto_desc("Arusha / Kilimanjaro", "Nairobi")),
    ("Zanzibar",             "Nairobi",       auto_desc("Zanzibar",             "Nairobi")),
    ("Dar es Salaam",        "Johannesburg",  auto_desc("Dar es Salaam",        "Johannesburg")),
    ("Dar es Salaam",        "Cape Town",     auto_desc("Dar es Salaam",        "Cape Town")),
    ("Zanzibar",             "Johannesburg",  auto_desc("Zanzibar",             "Johannesburg")),
    ("Dar es Salaam",        "Dubai",         auto_desc("Dar es Salaam",        "Dubai")),
    ("Dar es Salaam",        "Abu Dhabi",     auto_desc("Dar es Salaam",        "Abu Dhabi")),
    ("Zanzibar",             "Dubai",         auto_desc("Zanzibar",             "Dubai")),
]

# ── Tanzania Accordion (5 sections) ───────────────────────────────────────────

TANZANIA_ACCORDION = {
    "asia": [
        ("Dar es Salaam",        "Delhi"),
        ("Dar es Salaam",        "Mumbai"),
        ("Dar es Salaam",        "Chennai"),
        ("Dar es Salaam",        "Hyderabad"),
        ("Dar es Salaam",        "Bengaluru"),
        ("Dar es Salaam",        "Kochi"),
        ("Dar es Salaam",        "Vellore"),
        ("Zanzibar",             "Delhi"),
        ("Zanzibar",             "Mumbai"),
        ("Zanzibar",             "Chennai"),
        ("Zanzibar",             "Hyderabad"),
        ("Zanzibar",             "Kochi"),
        ("Arusha / Kilimanjaro", "Delhi"),
        ("Arusha / Kilimanjaro", "Mumbai"),
        ("Arusha / Kilimanjaro", "Chennai"),
        ("Dar es Salaam",        "Kolkata"),
        ("Dar es Salaam",        "Ahmedabad"),
        ("Dar es Salaam",        "Chandigarh"),
        ("Dar es Salaam",        "Dhaka"),
        ("Dar es Salaam",        "Karachi"),
        ("Dar es Salaam",        "Colombo"),
        ("Dar es Salaam",        "Bangkok"),
        ("Dar es Salaam",        "Singapore"),
        ("Dar es Salaam",        "Kuala Lumpur"),
        ("Zanzibar",             "Singapore"),
        ("Zanzibar",             "Bangkok"),
        ("Dar es Salaam",        "Kathmandu"),
        ("Dar es Salaam",        "Male"),
        ("Dar es Salaam",        "Islamabad"),
        ("Dar es Salaam",        "Lahore"),
        ("Arusha / Kilimanjaro", "Singapore"),
        ("Arusha / Kilimanjaro", "Bangkok"),
        ("Dar es Salaam",        "Yangon"),
        ("Dar es Salaam",        "Mandalay"),
        ("Dar es Salaam",        "Jakarta"),
        ("Dar es Salaam",        "Manila"),
        ("Dar es Salaam",        "Tokyo"),
        ("Dar es Salaam",        "Seoul"),
        ("Dar es Salaam",        "Hong Kong"),
    ],
    "middle_east": [
        ("Dar es Salaam",        "Dubai"),
        ("Dar es Salaam",        "Abu Dhabi"),
        ("Dar es Salaam",        "Doha"),
        ("Dar es Salaam",        "Riyadh"),
        ("Dar es Salaam",        "Jeddah"),
        ("Dar es Salaam",        "Muscat"),
        ("Dar es Salaam",        "Kuwait City"),
        ("Dar es Salaam",        "Bahrain"),
        ("Dar es Salaam",        "Istanbul"),
        ("Dar es Salaam",        "Ankara"),
        ("Zanzibar",             "Dubai"),
        ("Zanzibar",             "Abu Dhabi"),
        ("Zanzibar",             "Doha"),
        ("Zanzibar",             "Riyadh"),
        ("Zanzibar",             "Muscat"),
        ("Arusha / Kilimanjaro", "Dubai"),
        ("Arusha / Kilimanjaro", "Doha"),
        ("Arusha / Kilimanjaro", "Abu Dhabi"),
        ("Dar es Salaam",        "Medina"),
        ("Dar es Salaam",        "Dammam"),
    ],
    "europe_usa": [
        ("Dar es Salaam",        "London"),
        ("Dar es Salaam",        "Manchester"),
        ("Dar es Salaam",        "Birmingham"),
        ("Dar es Salaam",        "Frankfurt"),
        ("Dar es Salaam",        "Munich"),
        ("Dar es Salaam",        "Berlin"),
        ("Dar es Salaam",        "Paris"),
        ("Dar es Salaam",        "Amsterdam"),
        ("Dar es Salaam",        "Zurich"),
        ("Dar es Salaam",        "Geneva"),
        ("Dar es Salaam",        "Rome"),
        ("Dar es Salaam",        "Milan"),
        ("Dar es Salaam",        "Madrid"),
        ("Dar es Salaam",        "Barcelona"),
        ("Dar es Salaam",        "Brussels"),
        ("Dar es Salaam",        "Vienna"),
        ("Dar es Salaam",        "Warsaw"),
        ("Zanzibar",             "London"),
        ("Zanzibar",             "Frankfurt"),
        ("Zanzibar",             "Paris"),
        ("Zanzibar",             "Amsterdam"),
        ("Arusha / Kilimanjaro", "London"),
        ("Arusha / Kilimanjaro", "Frankfurt"),
        ("Dar es Salaam",        "New York"),
        ("Dar es Salaam",        "Los Angeles"),
        ("Dar es Salaam",        "Chicago"),
        ("Dar es Salaam",        "Houston"),
        ("Dar es Salaam",        "Dallas"),
        ("Dar es Salaam",        "Toronto"),
        ("Dar es Salaam",        "Vancouver"),
        ("Zanzibar",             "New York"),
        ("Zanzibar",             "Toronto"),
    ],
    "oceania": [
        ("Dar es Salaam",        "Sydney"),
        ("Dar es Salaam",        "Melbourne"),
        ("Dar es Salaam",        "Brisbane"),
        ("Dar es Salaam",        "Perth"),
        ("Dar es Salaam",        "Auckland"),
        ("Zanzibar",             "Sydney"),
        ("Zanzibar",             "Melbourne"),
        ("Arusha / Kilimanjaro", "Sydney"),
        ("Arusha / Kilimanjaro", "Melbourne"),
        ("Dar es Salaam",        "Adelaide"),
        ("Dar es Salaam",        "Gold Coast"),
        ("Dar es Salaam",        "Christchurch"),
    ],
    "africa": [
        ("Dar es Salaam",        "Nairobi"),
        ("Dar es Salaam",        "Johannesburg"),
        ("Dar es Salaam",        "Cape Town"),
        ("Dar es Salaam",        "Addis Ababa"),
        ("Dar es Salaam",        "Lagos"),
        ("Dar es Salaam",        "Accra"),
        ("Dar es Salaam",        "Kampala"),
        ("Dar es Salaam",        "Kigali"),
        ("Dar es Salaam",        "Lusaka"),
        ("Dar es Salaam",        "Harare"),
        ("Dar es Salaam",        "Maputo"),
        ("Dar es Salaam",        "Blantyre"),
        ("Dar es Salaam",        "Port Louis"),
        ("Dar es Salaam",        "Victoria"),
        ("Dar es Salaam",        "Abuja"),
        ("Zanzibar",             "Nairobi"),
        ("Zanzibar",             "Johannesburg"),
        ("Zanzibar",             "Cape Town"),
        ("Zanzibar",             "Addis Ababa"),
        ("Zanzibar",             "Kampala"),
        ("Zanzibar",             "Port Louis"),
        ("Arusha / Kilimanjaro", "Nairobi"),
        ("Arusha / Kilimanjaro", "Johannesburg"),
        ("Arusha / Kilimanjaro", "Addis Ababa"),
        ("Dar es Salaam",        "Khartoum"),
        ("Dar es Salaam",        "Durban"),
        ("Dar es Salaam",        "Pretoria"),
        ("Dar es Salaam",        "Tunis"),
        ("Dar es Salaam",        "Casablanca"),
        ("Dar es Salaam",        "Cairo"),
        ("Dar es Salaam",        "Algiers"),
        ("Dar es Salaam",        "Dakar"),
        ("Zanzibar",             "Cairo"),
        ("Zanzibar",             "Lagos"),
    ],
}
